#!/bin/bash

# Get the Python file name without the extension
filename=$(basename "$PYFILE")
filename="${filename%.*}"

# Compile the Python file
python -m compileall -b $PYFILE

# Rename the output file to $PYFILEc
mv "${filename}.pyc" "${PYFILE}c"
